dependencies:
- name: .
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.1-JX-INFRA
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.89
- name: go-quick
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
